/// <reference path="./cloudflare-env.d.ts" />

// Custom worker that wraps the SvelteKit adapter-cloudflare worker and adds
// a `scheduled` handler for the cleanup cron.
//
// Why: adapter-cloudflare's generated worker (`build/worker.js`) only exports
// a `fetch` handler. We need a `scheduled` handler for the cron trigger in
// wrangler.jsonc. The official pattern is to re-export the generated worker
// and bolt on extra handlers here.
//
// Deploy: `wrangler deploy custom-worker.ts` (positional entry overrides the
// `main` field in wrangler.jsonc, which is the adapter's build target).
// Build first: `vite build` (writes build/worker.js + build/assets).
//
// The SvelteKit server bundle already imports `lib/s3/polyfill.ts` (via
// `lib/s3/client.ts`), so by the time `scheduled` fires, the AWS SDK's DOM
// globals are installed. `runCleanup` is imported directly here too.

// @ts-ignore `build/worker.js` is generated by `vite build`
import { default as svelteWorker } from './build/worker.js';

import { runCleanup } from './lib/s3/cleanup';

export default {
	async fetch(
		request: Request,
		env: CloudflareEnv,
		ctx: ExecutionContext,
	): Promise<Response> {
		return svelteWorker.fetch(request, env, ctx);
	},

	async scheduled(
		event: ScheduledController,
		env: CloudflareEnv,
		ctx: ExecutionContext,
	): Promise<void> {
		const cron = event.cron ?? 'unknown';
		const scheduledTime = event.scheduledTime ?? Date.now();
		console.log('[cron] cleanup tick', { cron, scheduledTime });

		try {
			const result = await runCleanup(env);
			console.log('[cron] cleanup complete', result);
		} catch (err) {
			console.error('[cron] cleanup failed', {
				cron,
				err: err instanceof Error ? err.message : String(err),
				stack: err instanceof Error ? err.stack : undefined,
			});
			// Re-throw so the platform records the failure and retries next
			// scheduled run (CF cron does not auto-retry on the same tick).
			throw err;
		}

		// ctx is unused but the type signature requires it
		void ctx;
	},
} satisfies ExportedHandler<CloudflareEnv>;
